

server:
  port: 80
  #port: 443
  servlet:
    session:
      timeout: 3h #ms毫秒 s秒 m分钟 h小时 d天
#  ssl:
#    enabled: true
#    key-store: classpath:https/luoshoushou.fun.jks
#    key-store-type: jks
#    key-store-password: baizc192837465


mybatis:
  mapper-locations: classpath:mapper/*

http-port: 80


